#!/usr/bin/env python

# Python libs
import sys, time

# numpy and scipy
import numpy as np

# OpenCV
import cv2
import rospy

# Publica imagenes de la camara o de un archivo de video
from sensor_msgs.msg import CompressedImage, Image


def main(args):
  rospy.init_node('camera', anonymous=True)
  pub = rospy.Publisher("/compressed_image", CompressedImage, queue_size=10)
  publish_rate = rospy.get_param('~publish_rate', 24)
  cap = cv2.VideoCapture(0)
  #cap = cv2.VideoCapture("/home/ernesto/Videos/video1.avi")
  cap.set(3, 640/2)
  cap.set(4, 480/2)
  rate = rospy.Rate(publish_rate)
  while not rospy.is_shutdown():
    # Capture frame-by-frame
    ret, frame = cap.read()
    img = frame
    #### Create CompressedIamge ####
    msg = CompressedImage()
    msg.header.stamp = rospy.Time.now()
    msg.format = "jpeg"
    msg.data = np.array(cv2.imencode('.jpg', img, [cv2.IMWRITE_JPEG_QUALITY, 60])[1]).tostring()
    pub.publish(msg)
    rate.sleep()

if __name__ == '__main__':
    try:
        main(sys.argv)
    except rospy.ROSInterruptException:
        pass



